### PR TITLE
Master rebase

### PR DESCRIPTION
**Pull request by julianallchin**

### CODE REVIEW

**Comment by julianallchin** [comment]
Why did we upgrade to wpilib version 2020? It takes _forever_ to install and it has compiler errors. I think it was a mistake.

**Comment by kavidey** [comment]
2019 is NOT competition legal meaning that we would NOT pass inspection. If we're using python, we HAVE to use 2020

**Comment by julianallchin** [comment]
THE workflow WILL NOT work WITH wpilib 2020

**Comment by julianallchin** [comment]
Can you approve this?

**Review by kavidey — APPROVED** [review]

**Pull request merged**
